### ISSUE TITLE
How I can add class to each header (<li>)?

### ISSUE THREAD

**Issue by ni3galave** [telega/react-scrollspy-ez#1]
Hi @telega 

I want to display the index content of the document and my index content contains nested headings but as per plugins headers constructed at the same level. 
For example:
This is my index:
```
1. Heading1
    1.1 sub-heading-1
    1.2 sub-heading-2
2. Heading2
3. Heading3
```

Our plugin generated HTML for the above index as follows:
```
<ul>
     <li>1. Heading1</li>
     <li>1.1 sub-heading-1</li>
     <li>1.1 sub-heading-1</li>
     <li>2. Heading2</li>
     <li>3. Heading3</li>
</ul>
```

So here, all sub-heading created at the same level where the main heading belongs. therefor I am unable to add specific styling to sub-heading in order to add padding-left to sub-heading element. Is there any way to add class to each `<li>` element?
Currently, it is displaying in the following format:

```
1. Heading1
1.1 sub-heading-1
1.2 sub-heading-2
2. Heading2
3. Heading3
```

BTW, nice plugin 👍  it's so easy to add doc section in any app with help of this plugin.

**Comment by telega** [comment]
I have updated the component. You can now pass classes from the Index to the menu by adding the class to the item eg:
`<h2 id="two" class="underline">
          Heading Two
        </h2>`
and adding an includeParentClasses=true prop to the <Scrollspy />

**Comment by ni3galave** [comment]
Awesome! Thanks for the quick fix.
